---
- name: install core python packages
  apt: name='{% raw %}{{ item }}{% endraw %}' state='latest'
  with_items:
    - 'python-dev'
    - 'python-pycurl'
    - 'python-setuptools'
    - 'python-pip'
    - 'python-software-properties'
    - 'python-virtualenv'
    - 'virtualenvwrapper'

- name: create virtualenvs directory
  file: path='/srv/virtualenvs' 
        state='directory'
        owner={% raw %}{{ runtime_user }}{% endraw %}
        group={% raw %}{{ runtime_group }}{% endraw %}
