---
- name: install required runtime packages from apt
  apt: pkg={% raw %}{{ item }}{% endraw %} state=latest
  with_items:
    - 'libxml2-dev'
    - 'libxslt1-dev'

- name: add nginx configuration for runtime
  template: src='nginx.site.j2' 
            dest='/etc/nginx/sites-available/{% raw %}{{ runtime_domain }}{% endraw %}'
  notify:
    - restart nginx
    - restart runtime

- name: enable nginx configuration for runtime
  file: src='/etc/nginx/sites-available/{% raw %}{{ runtime_domain }}{% endraw %}'
        dest='/etc/nginx/sites-enabled/{% raw %}{{ runtime_domain }}{% endraw %}'
        state=link 
  notify:
    - restart nginx
    - restart runtime

- name: set ownership of virtualenv
  file: path="/srv/virtualenvs/{% raw %}{{ project_name }}{% endraw %}"
        owner="{% raw %}{{ login_user }}{% endraw %}"
        group="{% raw %}{{ login_user }}{% endraw %}"
        state='directory'
        recurse=yes

- name: install runtime python requirements
  pip:  requirements='/srv/{% raw %}{{ project_name }}{% endraw %}/requirements.txt'
        virtualenv="{% raw %}{{ runtime_venv }}{% endraw %}"

  notify:
    - restart runtime

- name: install grunt
  npm: name='grunt-cli' global=yes state='latest'

- name: install compass
  command: gem install compass --pre

- name: install runtime node requirements
  npm:  name={% raw %}{{ item.name }}{% endraw %}
        version={% raw %}{{ item.version }}{% endraw %}
        state=present
        path=/srv/{% raw %}{{ project_name }}{% endraw %}
  with_items:
    - { name: 'formwork',               version: 'https://github.com/marquee/formwork/tarball/v0.3.5'}
    - { name: 'shiny',                  version: 'https://github.com/alecperkins/sass-shiny/tarball/v0.9.0'}
    - { name: 'underscore',             version: '~1.6.0'}
    - { name: 'backbone',               version: '~1.1.2'}
    - { name: 'jquery',                 version: '~2.1.0'}
    - { name: 'URIjs',                  version: '~1.12.0'}
    - { name: 'cookie-component',       version: '~0.1.5' }
    - { name: 'browserify',             version: '~2.35.1'}
    - { name: 'coffee-script',          version: '~1.6.x'}
    - { name: 'coffeeify',              version: '~0.5.2'}
    - { name: 'grunt-browserify',       version: '~1.2.11'}
    - { name: 'grunt-contrib-compass',  version: '~0.6.0'}
    - { name: 'grunt-contrib-uglify',   version: '~0.2.5'}
    - { name: 'grunt-concurrent',       version: '~0.4.1'}
    - { name: 'grunt-contrib-watch',    version: '~0.5.3'}
    - { name: 'grunt-contrib-cssmin',   version: '~0.7.0'}
    - { name: 'grunt-env',              version: '~0.4.1'}
    - { name: 'grunt-shell',            version: '~0.6.1'}
    - { name: 'grunt-contrib-copy',     version: '~0.5.0'}
    - { name: 'viewport-units-buggyfill', version: '~0.3.1'}
  notify:
    - restart runtime

- name: build static files
  command: grunt build:production chdir=/srv/{% raw %}{{ project_name }}{% endraw %}
  notify:
    - restart runtime

- name: add rebuild_index to cron
  cron: name="rebuild index"
        minute=0 hour=0/2 day=* month=* weekday=*
        job="/srv/virtualenvs/{{ project_name }}/bin/python /srv/{% raw %}{{ project_name }}{% endraw %}/manage.py rebuild_index"
        state=present

- name: copy supervisor configuration for runtime
  template: src='supervisor-app.conf.j2' dest='/etc/supervisor/conf.d/{% raw %}{{ project_name }}{% endraw %}.conf'
  notify:
    - reload supervisor
    - restart runtime

- name: start runtime
  supervisorctl: name='{% raw %}{{ project_name }}{% endraw %}' state='started'
