---
- name: copy bash configuration
  template: src={% raw %}{{ item }}.j2 dest={{ login_dir }}/.{{ item }}{% endraw %}
  with_items:
    - bash_aliases
    - bash_colors
    - bash_helpers
    - bash_profile
