---
- name: install git
  apt: pkg=git-core state=latest

- name: clone repository
  git:
    repo={% raw %}{{ git_clone_url }}{% endraw %}
    dest=/srv/runtime
    accept_hostkey=True
  notify:
    - update git submodules
