VAGRANTFILE_API_VERSION = '2'

BOX     = 'trusty64'
BOX_URL = 'http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box       = BOX
    config.vm.box_url   = BOX_URL

    config.vm.define 'development' do |dev|
        dev.vm.hostname = '{{ project_name }}-dev'
        dev.vm.network 'private_network', ip: '{{ private_ip }}'
        dev.vm.synced_folder '.', '/srv/{{ project_name }}'
    end

    config.vm.provision :ansible do |ansible|
        ansible.inventory_path  = 'ops/inventory/development'
        ansible.extra_vars      = 'ops/vars/development'
        ansible.playbook        = 'ops/development.yml'
    end

    config.vm.provider 'virtualbox' do |vb|
        vb.memory = 512
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end

end
